name: Test Project

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository code
        uses: actions/checkout@v1

      - name: Install Java JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 1.15

      - name: Build with Gradle
        run: ./gradlew build
        env:
          EMAIL_HOST: smtp.example.com
          EMAIL_ADDRESS: email@example.com
          EMAIL_PASSWORD: ex@mple
          CLIENT_URL: http://localhost:3000

      - name: Test with Gradle
        run: ./gradlew test